/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PlatformIndexRouteImport } from './routes/_platform/index'
import { Route as PlatformPostsIndexRouteImport } from './routes/_platform/posts/index'
import { Route as PlatformPostsPostIdIndexRouteImport } from './routes/_platform/posts/$postId/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPostsIndexRoute = PlatformPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPostsPostIdIndexRoute =
  PlatformPostsPostIdIndexRouteImport.update({
    id: '/posts/$postId/',
    path: '/posts/$postId/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PlatformIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/posts/': typeof PlatformPostsIndexRoute
  '/posts/$postId/': typeof PlatformPostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PlatformIndexRoute
  '/auth': typeof AuthIndexRoute
  '/posts': typeof PlatformPostsIndexRoute
  '/posts/$postId': typeof PlatformPostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_platform/': typeof PlatformIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_platform/posts/': typeof PlatformPostsIndexRoute
  '/_platform/posts/$postId/': typeof PlatformPostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/auth/' | '/posts/' | '/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/posts' | '/posts/$postId'
  id:
    | '__root__'
    | '/_platform'
    | '/auth'
    | '/_platform/'
    | '/auth/'
    | '/_platform/posts/'
    | '/_platform/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_platform/': {
      id: '/_platform/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/posts/': {
      id: '/_platform/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PlatformPostsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/posts/$postId/': {
      id: '/_platform/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof PlatformPostsPostIdIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
  }
}

interface PlatformRouteRouteChildren {
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformPostsIndexRoute: typeof PlatformPostsIndexRoute
  PlatformPostsPostIdIndexRoute: typeof PlatformPostsPostIdIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformPostsIndexRoute: PlatformPostsIndexRoute,
  PlatformPostsPostIdIndexRoute: PlatformPostsPostIdIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
